#!/bin/sh
# the vcc helper script
# joshua higgins 2016

VCCIMAGE="kxes/pca2016"
SCRIPTURL="https://raw.githubusercontent.com/joshiggins/vccjs/master/vcc"

if test "$1" = 'update'; then
	echo ""
	echo ""
	echo "*********"
	echo 'checking for update to script'
	echo "*********"
	echo ""
	echo ""
	wget -O /usr/bin/vcc $SCRIPTURL
	if test "$?" = '0'; then
		echo "OK."
	else
			echo ""
			echo ""
			echo "*********"
			echo 'There was a problem updating. Check proxy settings.'
			echo "*********"
			echo ""
			echo ""
			exit 1
	fi
	echo ""
	echo ""
	echo "*********"
	echo 'pulling docker images'
	echo "*********"
	echo ""
	echo ""
	docker pull $VCCIMAGE
	if test "$?" = '0'; then
		echo "OK."
	else
			echo ""
			echo ""
			echo "*********"
			echo 'There was a problem updating. Check proxy settings.'
			echo "*********"
			echo ""
			echo ""
			exit 1
	fi
	exit 0
fi

if test "$1" = 'tool'; then
	if test "$2" = '--start'; then
		eval $(docker run --rm -it $VCCIMAGE $@)
	else
		docker run --rm -it $VCCIMAGE $@
	fi
fi

if test "$1" = 'shell'; then
	nids="`docker ps | grep $VCCIMAGE | awk '{print $1}' | wc -l`"
	if test "$nids" = '1'; then
		id="`docker ps | grep $VCCIMAGE | awk '{print $1}'`"
		echo ""
		echo ""
		echo "*********"
		echo "You are now entering the VCC shell for $id"
		echo "To exit, type \`exit\` or press CTRL+D"
		echo "*********"
		echo ""
		echo ""
		docker exec -it $id /bin/bash
	else
		echo "error: there is more than 1 VCC container running on this host"
		echo "use docker exec command to enter the container's shell"
	fi
	exit 0
fi